__target__: VelocityModule
frame_knn: 20
num_train_points: 512
feat_embedding_dim: 384
decoder_hidden_dim: 128
dsm_sigma: 0.01
use_global_feature: True
use_input_coords: True
normal_loss_weight: 0.4
tangent_damping_weight: 0.015
predict_num_steps: 1
predict_patch_size: 1600
predict_seed_k: 5
predict_seed_k_alpha: 1
