__target__: VelocityModule
encoder_type: pct_neighbor
frame_knn: 24
num_train_points: 256
feat_embedding_dim: 384
pct_attention_channels: 96
pct_num_attention_layers: 4
decoder_hidden_dim: 128
dsm_sigma: 0.01
loss_type: huber
huber_delta: 0.01
target_mode: clean_minus_noisy
loss_center_gamma: 2.0
use_global_feature: True
use_input_coords: True
predict_num_steps: 1
predict_patch_size: 1200
predict_seed_k: 5
predict_seed_k_alpha: 1
