__target__: VelocityModule
frame_knn: 20
num_train_points: 512
feat_embedding_dim: 384
decoder_hidden_dim: 128
dsm_sigma: 0.01
loss_type: huber
huber_delta: 0.01
target_mode: clean_minus_noisy
loss_center_gamma: 2.0
surface_loss_weight: 0.02
surface_planarity_power: 1.0
surface_curvature_suppress: 20.0
target_tangent_weight: 0.9
teacher_ckpt: experiments/vm_finetune/checkpoint_19.pkl
teacher_distill_weight: 2.0
teacher_distill_score_weight: 1.0
use_global_feature: True
use_input_coords: True
use_geometry_input: False
geometry_dim: 4
predict_num_steps: 1
predict_patch_size: 1600
predict_seed_k: 5
predict_seed_k_alpha: 1
