mode: predict
debug: False
load_ckpt: experiments/vm_pct_denoise_zero_residual/checkpoint_e0_s1200.pkl

components:
  data: predict_local_eval_testcats_100
  transform: predict
  model: vm_pct_denoise_zero_residual
  system: vm_pct_denoise_zero_residual

writer:
  __target__: vm
  save_dir: results_local_eval_testcats_100_pct_denoise_zero_residual_e0_s1200
  save_name: denoised
  output_format: npy
