mode: predict
debug: False
load_ckpt: experiments/vm_edge_pct_residual_score/warmstart_from_ft19.pkl

components:
  data: predict_local_eval_testcats_100
  transform: predict
  model: vm_edge_pct_residual_score
  system: vm_edge_pct_residual_score

writer:
  __target__: vm
  save_dir: results_local_eval_testcats_100_edge_pct_residual_score_warmstart
  save_name: denoised
  output_format: npy
