mode: predict
debug: False
load_ckpt: experiments/vm_field_ft/checkpoint_4.pkl

components:
  data: predict_local_eval_mesh_20
  transform: predict
  system: vm_field_ft
  model: vm_field_ft

writer:
  __target__: vm
  save_dir: results_local_eval_mesh_20_field4
  save_name: denoised
