mode: predict
debug: False
load_ckpt: experiments/vm_finetune/checkpoint_19.pkl

components:
  data: predict_local_eval_testcats_100
  transform: predict
  model: vm_robust_ft
  system: vm_finetune

writer:
  __target__: vm
  save_dir: results_local_eval_testcats_100_ft19
  save_name: denoised
  output_format: npy
