mode: predict
debug: False
load_ckpt: experiments/vm_multiscale_ft/checkpoint_0.pkl

components:
  data: predict_local_eval_mesh_20
  transform: predict
  system: vm_multiscale_ft
  model: vm_multiscale_ft

writer:
  __target__: vm
  save_dir: results_local_eval_mesh_20_multiscale_0
  save_name: denoised
