mode: predict
debug: False
load_ckpt: experiments/vm_robust/checkpoint_159.pkl

components:
  data: predict
  transform: predict
  system: vm_robust
  model: vm_robust

writer:
  __target__: vm
  save_dir: results
  save_name: denoised
