mode: predict
debug: False
load_ckpt: experiments/vm_finetune/checkpoint_24.pkl

components:
  data: predict_local_eval_mesh_20
  transform: predict
  system: vm_finetune
  model: vm_robust_ft

writer:
  __target__: vm
  save_dir: results_local_eval_mesh_20_ft24
  save_name: denoised
