mode: predict
debug: False
load_ckpt: experiments/vm_score_dsm_cont/checkpoint_e0_s500.pkl

components:
  data: predict_local_eval_mesh_20
  transform: predict
  system: vm_score_dsm_cont
  model: vm_score_dsm_1step

writer:
  __target__: vm
  save_dir: results_local_eval_mesh_20_score_dsm_cont_e0_s500_1step
  save_name: denoised
