mode: predict
debug: False
load_ckpt: experiments/vm_pct_denoise/checkpoint_e0_s200.pkl

components:
  data: predict_local_eval_mesh_20
  transform: predict
  model: vm_pct_denoise
  system: vm_pct_denoise

writer:
  __target__: vm
  save_dir: results_local_eval_mesh_20_pct_denoise_e0_s200
  save_name: denoised
  output_format: npy
