mode: predict
debug: False
load_ckpt: experiments/vm_refiner_pct_neighbor_pointgate_ft19/checkpoint_e0_s100.pkl

components:
  data: predict
  transform: predict
  system: vm_refiner_pct_neighbor_pointgate_ft19
  model: vm_refiner_pct_neighbor_pointgate_ft19

writer:
  __target__: vm
  save_dir: results_test_pct_pointgate
  save_name: denoised
  output_format: npy
