mode: predict
debug: False
load_ckpt: experiments/vm_refiner_pct_hier_trust_ft19/checkpoint_e0_s100.pkl

components:
  data: predict_local_eval_testcats_100
  transform: predict
  model: vm_refiner_pct_hier_trust_ft19
  system: vm_refiner_pct_hier_trust_ft19

writer:
  __target__: vm
  save_dir: results_local_eval_testcats_100_refiner_pct_hier_trust_ft19_e0_s100
  save_name: denoised
  output_format: npy
