mode: predict
debug: False
load_ckpt: experiments/vm_pct_denoise_direct/checkpoint_e0_s300.pkl

components:
  data: predict_local_eval_testcats_100
  transform: predict
  model: vm_pct_denoise_direct
  system: vm_pct_denoise_direct

writer:
  __target__: vm
  save_dir: results_local_eval_testcats_100_pct_denoise_direct_e0_s300
  save_name: denoised
  output_format: npy
