mode: predict
debug: False
load_ckpt: experiments/alpha_gate_refiner_pct_neighbor/checkpoint_7.pkl

components:
  data: predict_official_low
  transform: predict
  model: alpha_gate_refiner_pct_neighbor
  system: alpha_gate_refiner

writer:
  __target__: vm
  save_dir: results_official_low_alpha_gate_final
  save_name: denoised
  output_format: npy
