mode: predict
debug: False
load_ckpt: experiments/low_noise_refiner_residual/checkpoint_e0_s1500.pkl

components:
  data: predict_official_low
  transform: predict
  system: low_noise_refiner_residual
  model: low_noise_refiner_pct_neighbor

writer:
  __target__: vm
  save_dir: results_official_low_low_noise_refiner_residual_e0_s1500
  save_name: denoised
