mode: predict
debug: False
load_ckpt: experiments/vm_finetune/checkpoint_19.pkl

components:
  data: predict_local_eval_mesh_20
  transform: predict
  system: vm_finetune
  model: vm_robust_ft_disp_weighted

writer:
  __target__: vm
  save_dir: results_local_eval_mesh_20_ft19_disp_weighted
  save_name: denoised
