mode: predict
debug: False
load_ckpt: experiments/vm_surface_ft/checkpoint_e0_s300.pkl

components:
  data: predict_local_eval_mesh_20
  transform: predict
  system: vm_surface_ft
  model: vm_surface_ft

writer:
  __target__: vm
  save_dir: results_local_eval_mesh_20_surface_e0_s300
  save_name: denoised
  output_format: npy
