mode: predict
debug: False
load_ckpt: experiments/vm_noise_ft/checkpoint_0.pkl

components:
  data: predict_local_eval_mesh_20
  transform: predict
  system: vm_noise_ft
  model: vm_noise_ft

writer:
  __target__: vm
  save_dir: results_local_eval_mesh_20_noise_0
  save_name: denoised
