mode: predict
debug: False
load_ckpt: experiments/vm_robust/checkpoint_9.pkl

components:
  data: predict_local_eval_10
  transform: predict
  system: vm_robust
  model: vm_robust

writer:
  __target__: vm
  save_dir: results_local_eval_10
  save_name: denoised
