mode: predict
debug: False
load_ckpt: experiments/vm_score_teacher_ft/checkpoint_e0_s200.pkl

components:
  data: predict_local_eval_mesh_20
  transform: predict
  system: vm_score_teacher_ft
  model: vm_score_teacher_ft

writer:
  __target__: vm
  save_dir: results_local_eval_mesh_20_score_teacher_e0_s200
  save_name: denoised
  output_format: npy
