mode: predict
debug: False
load_ckpt: experiments/vm_pct_neighbor/checkpoint_e0_s500.pkl

components:
  data: predict_local_eval_mesh_20
  transform: predict
  system: vm_pct_neighbor
  model: vm_pct_neighbor

writer:
  __target__: vm
  save_dir: results_local_eval_mesh_20_pct_neighbor_e0_s500
  save_name: denoised
