mode: predict
debug: False
load_ckpt: experiments/vm_refiner_pct_denoise_pointgate_ft19/checkpoint_e0_s200.pkl

components:
  data: predict_local_eval_mesh_20
  transform: predict
  model: vm_refiner_pct_denoise_pointgate_ft19
  system: vm_refiner_pct_denoise_pointgate_ft19

writer:
  __target__: vm
  save_dir: results_local_eval_mesh_20_refiner_pct_denoise_pointgate_ft19_e0_s200
  save_name: denoised
  output_format: npy
