mode: predict
debug: False
load_ckpt: experiments/vm_score_hybrid_ft/checkpoint_e0_s100.pkl

components:
  data: predict_local_eval_mesh_20
  transform: predict
  system: vm_score_hybrid_ft
  model: vm_score_hybrid_ft

writer:
  __target__: vm
  save_dir: results_local_eval_mesh_20_score_hybrid_e0_s100
  save_name: denoised
  output_format: npy
