mode: predict
debug: False
load_ckpt: experiments/vm_finetune/checkpoint_19.pkl

components:
  data: predict
  transform: predict
  system: vm_finetune
  model: vm_robust_ft

writer:
  __target__: vm
  save_dir: results_test_ft19
  save_name: denoised
  output_format: npy
