mode: train
debug: False

components:
  data: train_smoke
  transform: finetune_score_hybrid
  model: vm_edge_pct_ms_score
  system: vm_edge_pct_ms_score

loss:
  loss: 1.0

optimizer:
  __target__: adam
  lr: 0.00008

trainer:
  epochs: 1
  save_every: 0
  save_every_steps: 0
  lr_decay: 1.0
  loss_ema_alpha: 0.98
