mode: predict
debug: False
load_ckpt: experiments/vm/checkpoint_0.pkl

components:
  data: predict_smoke
  transform: predict
  system: vm
  model: vm

writer:
  __target__: vm
  save_dir: results_smoke
  save_name: denoised
