mode: train
debug: False

components:
  data: train_smoke
  transform: robust
  system: vm_robust
  model: vm_robust

loss:
  loss: 1.0

optimizer:
  __target__: adam
  lr: 0.0001

trainer:
  epochs: 1
  save_every: 1
