mode: train
debug: False

components:
  data: train_fast_b8
  transform: finetune_normal
  model: vm_refiner_pct_denoise_free_ft19
  system: vm_refiner_pct_denoise_free_ft19

loss:
  loss: 1.0

optimizer:
  __target__: adam
  lr: 0.00004

trainer:
  epochs: 4
  save_every: 1
  save_every_steps: 200
  lr_decay: 0.5
  lr_decay_every: 2
  loss_ema_alpha: 0.98
