mode: train
debug: False
load_ckpt: experiments/vm_finetune/checkpoint_19.pkl

components:
  data: train_fast
  transform: finetune_score_hybrid
  system: vm_score_hybrid_ft
  model: vm_score_hybrid_ft

loss:
  loss: 1.0

optimizer:
  __target__: adam
  lr: 0.000005

trainer:
  epochs: 6
  save_every: 1
  save_every_steps: 100
  lr_decay: 0.5
  lr_decay_every: 3
  loss_ema_alpha: 0.98
