mode: train
debug: False

components:
  data: train_fast
  transform: score_dsm
  model: vm_score_dsm
  system: vm_score_dsm

loss:
  loss: 1.0

optimizer:
  __target__: adam
  lr: 0.0002

trainer:
  epochs: 20
  save_every: 1
  save_every_steps: 100
  lr_decay: 0.5
  lr_decay_every: 8
  loss_ema_alpha: 0.98
