mode: train
debug: False

components:
  data: train_fast_b8
  transform: finetune_narrow_noise
  system: vm_p2_alphagate
  model: vm_alphagate_ft

loss:
  loss: 1.0

optimizer:
  __target__: adam
  lr: 0.0003

trainer:
  epochs: 10
  save_every: 2
  lr_decay: 0.7
  lr_decay_every: 4
